### ISSUE TITLE
GIFs doesn't seem to resize properly at special scenarios and starts flickering

### ISSUE THREAD

**Issue by Tarek1337** [discordapp/lilliput#27]
Here is a few examples: 
https://cdn.discordapp.com/attachments/155491653858230273/423000223615287316/21312.gif
https://cdn.discordapp.com/attachments/420995378582913030/431850348647415818/trelloderpy.gif

They look fine in the browser, but for an example. Try to paste this into Discord and they will start flickering.

**Comment by brian-armstrong-discord** [comment]
This is a known bug. These gifs have frames where only part of the frame is drawn. lilliput doesn't draw partial frames, instead of fills the non-partial areas with transparency. But if the gif doesnt have transparency in the palette for that frame, then instead it will draw nonsensical colors in the blank spots.
